REVOKE ALL ON FUNCTION public.write_audit(text, text, uuid, jsonb, jsonb, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.block_audit_mutation() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.audit_profiles() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.audit_user_roles() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.audit_teams() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.audit_team_collaborators() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.audit_facilities() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.audit_app_settings() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.enforce_collaborator() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.enforce_profile_update() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.enforce_team_leader() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.can_manage_profile(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.leader_team_id(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.my_primary_team_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_profile(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.leader_team_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_primary_team_id() TO authenticated;