/**
 * CEN 1.0 — M1.5 Permission model (nguồn duy nhất cho UI và backend).
 *
 * Nguyên tắc:
 * - Chỉ 4 vai trò hiện hành: admin, cmo, leader, member.
 * - Ma trận dưới đây phản ánh đúng quyền đã triển khai ở M1.4 (không mở rộng).
 * - UI dùng để ẩn/disable; server function và RLS vẫn kiểm tra độc lập.
 */
export type AppRoleKey = "admin" | "cmo" | "leader" | "member";

export const ROLE_ORDER: AppRoleKey[] = ["admin", "cmo", "leader", "member"];

export const PERMISSIONS = {
  MEMBERS_VIEW: "members.view",
  MEMBERS_CREATE: "members.create",
  MEMBERS_EDIT_SCOPED: "members.edit_scoped",
  MEMBERS_LOCK: "members.lock",
  ROLES_VIEW: "roles.view",
  ROLES_ASSIGN: "roles.assign",
  ORG_VIEW: "organization.view",
  ORG_MANAGE: "organization.manage",
  SETTINGS_ADMIN: "settings.admin",
  AUDIT_VIEW: "audit.view",
  PROJECTS_VIEW: "projects.view",
  PROJECTS_CREATE: "projects.create",
  PROJECTS_APPROVE_LEADER: "projects.approve_leader",
  PROJECTS_APPROVE_CMO: "projects.approve_cmo",
  TASKS_VIEW: "tasks.view",
  TASKS_CREATE: "tasks.create",
  REPORTS_VIEW: "reports.view",
  REPORTS_SUBMIT_DAILY: "reports.submit_daily",
  REPORTS_REVIEW_DAILY: "reports.review_daily",
  REPORTS_SUBMIT_WEEKLY: "reports.submit_weekly",
  REPORTS_REVIEW_WEEKLY: "reports.review_weekly",
  TELEGRAM_MANAGE: "telegram.manage",
  MVP_VIEW: "mvp.view",
  MVP_VOTE: "mvp.vote",
  MVP_REVIEW: "mvp.review",
  MVP_APPROVE: "mvp.approve",
  MVP_MANAGE: "mvp.manage",
  ANNOUNCEMENTS_VIEW: "announcements.view",
  ANNOUNCEMENTS_CREATE: "announcements.create",
} as const;


export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LABEL: Record<PermissionKey, string> = {
  "members.view": "Xem danh sách thành viên",
  "members.create": "Tạo tài khoản thành viên",
  "members.edit_scoped": "Sửa hồ sơ thành viên trong phạm vi",
  "members.lock": "Khóa / mở khóa tài khoản",
  "roles.view": "Xem vai trò và quyền",
  "roles.assign": "Gán vai trò hệ thống",
  "organization.view": "Xem Team và Cơ sở",
  "organization.manage": "Tạo / sửa Team và Cơ sở",
  "settings.admin": "Cấu hình quản trị hệ thống",
  "audit.view": "Xem nhật ký hoạt động",
  "projects.view": "Xem dự án trong phạm vi",
  "projects.create": "Tạo dự án",
  "projects.approve_leader": "Duyệt dự án ở bước Leader",
  "projects.approve_cmo": "Duyệt dự án ở bước CMO",
  "tasks.view": "Xem công việc trong phạm vi",
  "tasks.create": "Tạo công việc",
  "reports.view": "Xem báo cáo trong phạm vi",
  "reports.submit_daily": "Gửi báo cáo ngày",
  "reports.review_daily": "Duyệt báo cáo ngày",
  "reports.submit_weekly": "Gửi báo cáo tuần của Team",
  "reports.review_weekly": "Duyệt báo cáo tuần",
  "telegram.manage": "Quản lý kết nối Telegram",
  "mvp.view": "Xem MVP và danh hiệu",
  "mvp.vote": "Bỏ phiếu MVP",
  "mvp.review": "Chấm điểm đánh giá thực tế",
  "mvp.approve": "Phê duyệt và công bố danh hiệu",
  "mvp.manage": "Quản lý kỳ MVP và dữ liệu chấm điểm",
  "announcements.view": "Xem thông báo nội bộ",
  "announcements.create": "Soạn và phát hành thông báo nội bộ",
};

export const PERMISSION_GROUP: Record<PermissionKey, string> = {
  "members.view": "Thành viên",
  "members.create": "Thành viên",
  "members.edit_scoped": "Thành viên",
  "members.lock": "Thành viên",
  "roles.view": "Vai trò",
  "roles.assign": "Vai trò",
  "organization.view": "Tổ chức",
  "organization.manage": "Tổ chức",
  "settings.admin": "Hệ thống",
  "audit.view": "Hệ thống",
  "projects.view": "Dự án",
  "projects.create": "Dự án",
  "projects.approve_leader": "Dự án",
  "projects.approve_cmo": "Dự án",
  "tasks.view": "Công việc",
  "tasks.create": "Công việc",
  "reports.view": "Báo cáo",
  "reports.submit_daily": "Báo cáo",
  "reports.review_daily": "Báo cáo",
  "reports.submit_weekly": "Báo cáo",
  "reports.review_weekly": "Báo cáo",
  "telegram.manage": "Hệ thống",
  "mvp.view": "MVP và danh hiệu",
  "mvp.vote": "MVP và danh hiệu",
  "mvp.review": "MVP và danh hiệu",
  "mvp.approve": "MVP và danh hiệu",
  "mvp.manage": "MVP và danh hiệu",
  "announcements.view": "Thông báo nội bộ",
  "announcements.create": "Thông báo nội bộ",
};

/** Ma trận quyền — giữ nguyên phạm vi đã chốt ở M1.4. */
export const ROLE_PERMISSIONS: Record<AppRoleKey, PermissionKey[]> = {
  admin: [
    "members.view",
    "members.create",
    "members.edit_scoped",
    "members.lock",
    "roles.view",
    "roles.assign",
    "organization.view",
    "organization.manage",
    "settings.admin",
    "audit.view",
    "projects.view",
    "projects.create",
    "projects.approve_leader",
    "projects.approve_cmo",
    "tasks.view",
    "tasks.create",
    "reports.view",
    "reports.submit_daily",
    "reports.review_daily",
    "reports.review_weekly",
    "telegram.manage",
    "mvp.view",
    "mvp.vote",
    "announcements.view",
    "announcements.create",
    "mvp.manage",
  ],
  cmo: [
    "members.view",
    "members.create",
    "members.edit_scoped",
    "roles.view",
    "roles.assign",
    "organization.view",
    "audit.view",
    "projects.view",
    "projects.create",
    "projects.approve_cmo",
    "tasks.view",
    "tasks.create",
    "reports.view",
    "reports.submit_daily",
    "reports.review_daily",
    "reports.review_weekly",
    "mvp.view",
    "mvp.vote",
    "announcements.view",
    "announcements.create",
    "mvp.review",
    "mvp.approve",
    "mvp.manage",
  ],
  leader: [
    "members.view",
    "members.edit_scoped",
    "roles.view",
    "organization.view",
    "projects.view",
    "projects.create",
    "projects.approve_leader",
    "tasks.view",
    "tasks.create",
    "reports.view",
    "reports.submit_daily",
    "reports.review_daily",
    "reports.submit_weekly",
    "mvp.view",
    "mvp.vote",
    "announcements.view",
    "announcements.create",
    "mvp.review",
  ],
  member: [
    "organization.view",
    "projects.view",
    "projects.create",
    // Member là người phụ trách Task: phải xem và tự nhận việc (RLS/trigger đã cho phép).
    "tasks.view",
    "tasks.create",
    "reports.view",
    "reports.submit_daily",
    "mvp.view",
    "mvp.vote",
    "announcements.view",
    "announcements.create",
  ],
};

export function hasPermission(role: AppRoleKey | null, permission: PermissionKey): boolean {
  if (!role) return false;
  return ROLE_PERMISSIONS[role].includes(permission);
}

export const PERMISSION_DENIED_MESSAGE = "Bạn không có quyền thực hiện thao tác này.";
